wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    code_path: code/scripts/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.4
      5: 0.10.27
      8:
      - 5
more:
  desc: null
  value: custom
